import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import AuthProvider from "@/services/AuthProvider";
import { Toaster } from "@/components/ui/toaster"
import NextTopLoader from 'nextjs-toploader';
import ClientProvider from "@/queryProvider/page";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Tutor Master",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-[2200px] w-full text-[#424242] mx-auto bg-[#F5F5F5]`}
      >
        <AuthProvider>
        <Toaster />
        <NextTopLoader template='<div class="bar" role="bar"><div class="peg"></div></div>' speed={500} height={4}/>

        <ClientProvider>

        <Navbar></Navbar>
        {children}
        <Footer/>


        </ClientProvider>

        

        </AuthProvider>
      
      </body>
    </html>
  );
}
